/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hoc2;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java_cup.runtime.Symbol;

/**
 *
 * @author ignac
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jAreaSigma = new javax.swing.JTextArea();
        btnLex = new javax.swing.JButton();
        btnSintac = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jAreaLex = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jAreaSintac = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cadena a analizar sintácticamente");

        jAreaSigma.setColumns(20);
        jAreaSigma.setRows(5);
        jScrollPane1.setViewportView(jAreaSigma);

        btnLex.setText("Analizar Lexicamente");
        btnLex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLexActionPerformed(evt);
            }
        });

        btnSintac.setText("Analizar Sintacticamente");
        btnSintac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSintacActionPerformed(evt);
            }
        });

        jAreaLex.setColumns(20);
        jAreaLex.setRows(5);
        jScrollPane2.setViewportView(jAreaLex);

        jAreaSintac.setColumns(20);
        jAreaSintac.setRows(5);
        jScrollPane3.setViewportView(jAreaSintac);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLex)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSintac)
                        .addGap(125, 125, 125))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLex)
                    .addComponent(btnSintac))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLexActionPerformed
        // TODO add your handling code here:
        Symbol simb;
        String Lexema = new String();
        String CadAux = new String();
        File ArchEntrada = new File("ArchEntrada.txt");
        PrintWriter escribir;
        jAreaLex.setText("");
        jAreaSintac.setText("");
        try {
            escribir = new PrintWriter(ArchEntrada);
            escribir.print(jAreaSigma.getText());
            escribir.close();
        } catch (FileNotFoundException e) {
            //System.Logger.getLogger(FrmPrincipal.class.getName()).log(Level.SEVERE, null, e);
        }
        try {
            Reader lector;
            lector = new BufferedReader(new FileReader("ArchEntrada.txt"));
            
            AnalizadorLexico AnalizLexico = new AnalizadorLexico(lector);
            do {          
                simb = AnalizLexico.next_token();
                CadAux = Integer.toString(simb.sym);
                Lexema = AnalizLexico.yytext();
                if(simb.sym == AnalizadorSintacticoSym.EOF)
                    CadAux = "Token: " + CadAux + "\tIdentTOKEN: FIN\n";
                else
                    switch(simb.sym){
                        case AnalizadorSintacticoSym.Enter:
                            CadAux = "Token: " + CadAux + "\tIdentTOKEN: Enter\t Lexema: " + Lexema;
                            break;
                        case AnalizadorSintacticoSym.NUM:
                            CadAux = "Token: " + CadAux + "\tIdentTOKEN: NUM\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.OpSuma:
                            CadAux = "Token: " + CadAux + "\tIdentTOKEN: OpSuma\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.OpResta:
                            CadAux = "Token: " + CadAux + "\tIdentTOKEN: OpResta\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.OpProd:
                            CadAux = "Token: " + CadAux + "\tIdentTOKEN: OpProd\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.OpDiv:
                            CadAux = "Token: " + CadAux + "\tIdentTOKEN: OpDiv\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.ParIzq:
                            CadAux = "Token: " + CadAux + "\tIdentTOKEN: ParIzq\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.ParDer:
                            CadAux = "Token: " + CadAux + "\tIdentTOKEN: ParDer\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.error:
                            CadAux = "Token: " + CadAux + "\tIdentTOKEN: ERROR\t Lexema: " + Lexema + "\n";
                            break;
                        case AnalizadorSintacticoSym.OpAsig:
                            CadAux = "Token: " + CadAux + "\tIdentTOKEN: OpAsig\t Lexema: " + Lexema + "\n";
                            break;  
                        case AnalizadorSintacticoSym.VAR:
                            CadAux = "Token: " + CadAux + "\tIdentTOKEN: VAR\t Lexema: " + Lexema + " indice = " + Integer.toString((Integer)simb.value) + "\n";
                            break;
                        default:
                            CadAux = "Token: " + CadAux + "\tIdentTOKEN: OTRO\t Lexema: " + AnalizLexico.yytext() + "\n";                  
                    }
                jAreaLex.append(CadAux);
            } while (simb.sym != AnalizadorSintacticoSym.EOF);
        } catch (IOException e) {
            jAreaLex.append("Error Caught\n");
        }
    }//GEN-LAST:event_btnLexActionPerformed

    private void btnSintacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSintacActionPerformed
        // TODO add your handling code here:
        try {
            AnalizadorSintactico Sintac = new AnalizadorSintactico(
                    new AnalizadorLexico(new FileReader("ArchEntrada.txt")));
            Sintac.frmInterfaz = this;
            
            Object result = Sintac.parse().value;
            jAreaSintac.append("\n Fin del análisis sintáctico");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSintacActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmPrincipal().setVisible(true);
//            }
//        });
        FrmPrincipal frmInterfaz = new FrmPrincipal();
        frmInterfaz.setVisible(true);
    }
    
    public void PonerTextSintac(String texto){
        jAreaSintac.append(texto);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLex;
    private javax.swing.JToggleButton btnSintac;
    private javax.swing.JTextArea jAreaLex;
    private javax.swing.JTextArea jAreaSigma;
    private javax.swing.JTextArea jAreaSintac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
